const LightMode = {
  primary: "#FEFEFE",
  secondary: "#497AFC",
  third: "#ee82ee",
  separator: "#c8c7cc",
  textDecorationLine: "#305cf7",
  description: "#7E7C7C",
  leftActionGreen: "#388e3c",
  leftActionBlue: "#497AFC",
  message: "#999",
  border: "#999",
  grey: "#C8C7CD",
  yellow: "#ffab00",
  red: "#dd2c00",
  text: "#161616",
  disabled: "#C8C7CD",
  transparent: "#00000040",
  background: "#F2F2F2",
  item: "#FFFFFF",
  icon: "#C8C7CD",
}

const DarkMode = {
  primary: "#101010",
  secondary: "#497AFC",
  third: "#B96FB9",
  separator: "#3A3A3A",
  textDecorationLine: "#81A7F7",
  description: "#CCCCCC",
  leftActionGreen: "#66BB6A",
  leftActionBlue: "#82AFFF",
  message: "#E0E0E0",
  border: "#FAFAFA",
  grey: "#444444",
  yellow: "#FFD740",
  red: "#FF5252",
  text: "#FFFFFF",
  disabled: "#666666",
  transparent: "#FFFFFF40",
  background: "#202020",
  item: "#666666",
  icon: "#CCCCCC",
};

export const ThemeColors = (theme: string) => {
  return {
    primary: theme == "light" ? LightMode.primary : DarkMode.primary,
    secondary: theme == "light" ? LightMode.secondary : DarkMode.secondary,
    third: theme == "light" ? LightMode.third : DarkMode.third,
    separator: theme == "light" ? LightMode.separator : DarkMode.separator,
    textDecorationLine: theme == "light" ? LightMode.textDecorationLine : DarkMode.textDecorationLine,
    description: theme == "light" ? LightMode.description : DarkMode.description,
    leftActionGreen: theme == "light" ? LightMode.leftActionGreen : DarkMode.leftActionGreen,
    leftActionBlue: theme == "light" ? LightMode.leftActionBlue : DarkMode.leftActionBlue,
    message: theme == "light" ? LightMode.message : DarkMode.message,
    border: theme == "light" ? LightMode.border : DarkMode.border,
    grey: theme == "light" ? LightMode.grey : DarkMode.grey,
    yellow: theme == "light" ? LightMode.yellow : DarkMode.yellow,
    red: theme == "light" ? LightMode.red : DarkMode.red,
    text: theme == "light" ? LightMode.text : DarkMode.text,
    disabled: theme == "light" ? LightMode.disabled : DarkMode.disabled,
    transparent: theme == "light" ? LightMode.transparent : DarkMode.transparent,
    background: theme == "light" ? LightMode.background : DarkMode.background,
    item: theme == "light" ? LightMode.item : DarkMode.item,
    icon: theme == "light" ? LightMode.icon : DarkMode.icon,
  }
}